### ISSUE TITLE
UWP/Windows10 build fails when react-native-dialogflow module is imported.

### ISSUE THREAD

**Issue by npmun** [innFactory/react-native-dialogflow#40]
I am conditionally importing Dialogflow module in my project. However, "react-native run-windows" (react-native-windows) still fails because index.js (or index.windows.js) file missing. 

**This is how I am importing module:**

let Dialogflow_V2 = null;
if (Platform.OS === 'android' || Platform.OS === 'ios') {
    Dialogflow_V2 = require('react-native-dialogflow').Dialogflow_V2;
}

**And, here is the exception:**

_error: bundling failed: Error: While trying to resolve module `react-native-dialogflow` from file `W:\Projects\ReactNative\ServiceLinkMobile\src\containers\main\MainDisp.js`, the package `W:\Projects\ReactNative\ServiceLinkMobile\node_modules\react-native-dialogflow\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`W:\Projects\ReactNative\ServiceLinkMobile\node_modules\react-native-dialogflow\index`. Indeed, none of these files exist:

  * `W:\Projects\ReactNative\ServiceLinkMobile\node_modules\react-native-dialogflow\index(.native||.windows.js|.native.js|.js|.windows.json|.native.json|.json)`
  * `W:\Projects\ReactNative\ServiceLinkMobile\node_modules\react-native-dialogflow\index\index(.native||.windows.js|.native.js|.js|.windows.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:103:15)
    at DependencyGraph.resolveDependency (W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:374:16)
    at W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:313)
    at W:\Projects\ReactNative\ServiceLinkMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:473
    at <anonymous>_

**Comment by spoeck** [comment]
In version `3.2.0` I merged both index.xxx.js files to one index.js.
Could you try it with this version? If you still have this error, feel free to reopen this issue!
