### ISSUE TITLE
Could not resolve all files for configuration ':app:debugCompileClasspath'. Could not find sdk.aar (ai.api:sdk:2.0.7)

### ISSUE THREAD

**Issue by mawaisqr** [innFactory/react-native-dialogflow#62]
Hi guys, 
I am on ubuntu 18.04, and I'm using react native cli, my build process failed after adding `react-native-dialogflow` into my project. The same project was running successfully on my colleague Mac even after installing `react-native-dialogflow` but I don't know why it's giving me error.

I have searched this error but the solutions I found were for dialogflow android sdk, though I did tried some of thoes e.g. [https://github.com/dialogflow/dialogflow-android-client/issues/41](url) but these didn't helped me solved this error.

Following is the complete error. I would really appreciate any help from you guys.

<pre><font color="#EF2929"><b>&gt; Task :app:checkDebugClasspath</b></font><font color="#CC0000"> FAILED</font>

<font color="#CC0000">FAILURE: Build failed with an exception.</font>

* What went wrong:
Could not resolve all files for configuration &apos;:app:debugCompileClasspath&apos;.
<font color="#C4A000">&gt; </font>Could not find sdk.aar (ai.api:sdk:2.0.7).
  Searched in the following locations:
      file:/home/awais/.m2/repository/ai/api/sdk/2.0.7/sdk-2.0.7.aar

* Try:
Run with <b>--stacktrace</b> option to get the stack trace. Run with <b>--info</b> or <b>--debug</b> option to get more log output. Run with <b>--scan</b> to get full insights.

* Get more help at <b>https://help.gradle.org</b>

<font color="#EF2929"><b>BUILD FAILED</b></font> in 3s
1 actionable task: 1 executed
<font color="#CC0000">Could not install the app on the device, read the error above for details.</font>
<font color="#CC0000">Make sure you have an Android emulator running or a device connected and have</font>
<font color="#CC0000">set up your Android development environment:</font>
<font color="#CC0000">https://facebook.github.io/react-native/docs/getting-started.html</font>

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (/home/awais/Desktop/tmp/patientapp/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/home/awais/Desktop/tmp/patientapp/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/home/awais/Desktop/tmp/patientapp/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
</pre>

**Comment by mawaisqr** [comment]
Hi guys I'm closing this issue, 
For those who might face this issue, a simple fix for it is to download [http://central.maven.org/maven2/ai/api/sdk/2.0.7/sdk-2.0.7.aar](url) and then paste `sdk-2.0.7.aar` into the directory where build process was trying to find it, for me this directory was **/home/awais/.m2/repository/ai/api/sdk/2.0.7/sdk-2.0.7.aar**

Danke innFactory for library, tuchss :)
